version: 1.2.0
services:
  - mysql
  - php:
      version: 7.1

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

cde-databases:
  - blt_ode_demo
  - cddemo11

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer validate --no-check-all --ansi
              - composer install --ansi
              - source ${BLT_DIR}/scripts/pipelines/setup_env
              # - nvm install v6.9.1
              # - npm install --global yarn
        - validate:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/validate
        - setup-app:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/setup_app
        - tests:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/tests
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact
        - deploy:
            script:
              - pipelines-deploy
              - pipelines-sync-dbs blt_ode_demo cddemo11
  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy
            - pipelines-sync-dbs blt_ode_demo cddemo11
  pre-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy
            - pipelines-sync-dbs blt_ode_demo cddemo11
